version: '3'
services:
  rails_app:
    build: ./senteces_with_entities
    command: sh -c "rm -f tmp/pids/server.pid && bundle && bundle exec rake db:prepare && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./senteces_with_entities:/app
    ports:
      - "3000:3000"
    environment:
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
    depends_on:
      - postgres
  postgres:
    image: postgres:14.2-alpine
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
      - ./:/home
    ports:
      - "5450:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sentences_development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  db_postgres_data:
